config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  resources :projects do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  validates_presence_of :title, :description
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  validates_presence_of :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only:[:edit, :update, :show, :destroy]

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:success] = "Project was successfully created."
      redirect_to projects_path
    else
      render 'new'
    end
  end

  def edit
  end

  def show
    @task = @project.tasks.build
    @tasks = Task.where(project_id: @project.id)
  end

  def update
    if @project.update_attributes(project_params)
      flash[:success] = "Project was successfully updated."
      redirect_to project_path(@project)
    else
      render 'edit'
    end
  end

  def destroy
    if @project.destroy
      flash[:success] = "Project was successfully deleted."
      redirect_to root_path
    else
      flash[:info] = "Could not delete project. Please try again later."
      redirect_to project_path(@project)
    end
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_project

  def create
    @task = @project.tasks.build(task_params)
    if @task.save
      flash[:success] = "Task was successfully created."
      redirect_to @project
    else
      flash[:notice] = "Something went wrong. Please try again later."
      redirect_to @project
    end
  end

  private

  def find_project
    @project = Project.find(params[:project_id])
  end

  def task_params
    params.require(:task).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Taskboard", root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><%= link_to "Projects", root_path %></li>
        <li><a href="#">Page 1</a></li>
        <li><a href="#">Page 2</a></li>
        <li><a href="#">Page 3</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskboard</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <main>
        <%= render 'layouts/flash' %>
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Create a new project
  </div>
  <div class="panel-body">
    <%= form_for @project do |f| %>
      <%= f.text_field :title, placeholder: 'Project title', class: 'form-control', autofocus: true %>
      <% if @project.errors.any? %>
        <% @project.errors[:title].each do |msg| %>
          <p class="text-danger"><%= msg %></p>
        <% end %>
      <% else %>
        <br />
      <% end %>
      <%= f.text_field :description, placeholder: 'Project description', class: 'form-control' %>
      <% if @project.errors.any? %>
        <% @project.errors[:description].each do |msg| %>
          <p class="text-danger"><%= msg %></p>
        <% end %>
      <% else %>
        <br />
      <% end %>
      <br />
      <%= f.submit class: 'btn btn-success', name: button_name %>
      <% if @project.new_record? %>
        <%= link_to 'Cancel', projects_path, class: 'btn btn-danger' %>
      <% else %>
        <%= link_to 'Cancel', project_path(@project), class: 'btn btn-danger' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4 col-xs-12">
    <%= render 'form', button_name: 'Update Project' %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>
      Tasks Board
      <span class="pull-right">
        <%= link_to "New Project", new_project_path, class: 'btn btn-primary' %>
      </span>
    </h1>
  </div>
</div>

<% @projects.each_slice(3) do |project_group| %>
  <div class="row">
    <% project_group.each do |project| %>
      <div class="col-md-4">
        <div class="panel panel-primary">
          <div class="panel-heading"><%= project.title %></div>
          <div class="panel-body"><%= project.description %></div>
          <div class="panel-footer text-right">
            <%= link_to "Details", project_path(project), class: 'btn btn-sm btn-info' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/projects/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4 col-xs-12">
    <%= render 'form', button_name: 'Create Project' %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="row">
  <div class="col-md-10">
    <h1><%= @project.title %></h1>
    <h4><%= @project.description %></h4>
  </div>
  <div class="col-md-2 text-right">
    <%= link_to "Edit Project", edit_project_path(@project), class: 'btn btn-primary' %>
    <br />
    <br />
    <%= link_to "Delete Project", project_path(@project), class: 'btn btn-danger', method: :delete, data: {confirm: "Are you sure you want to delete #{@project.title}?"} %>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        Tasks
      </div>
      <% @tasks.each do |task| %>
        <div class="panel panel-success">
          <div class="panel-heading">
            <%= task.title %>
          </div>
        </div>
      <% end %>
      <%= form_for [@project, @task] do |f| %>
        <div class="input-group">
          <%= f.text_field :title, class: 'form-control' %>
          <span class="input-group-btn">
            <%= f.submit 'Add Task', class: 'btn btn-primary' %>
          </span>
        </div>
      <% end %>
      </div>
  </div>
</div>

app/views/tasks/_task.html.erb
<div class="panel panel-success">
  <div class="panel-heading">
    <%= task.title %>
  </div>
</div>